"""add bluelink fields to vehicle_status

Revision ID: bfb6a6a2e86b
Revises: c9a8516ab1ca
Create Date: 2025-12-08 11:12:46.756110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfb6a6a2e86b'
down_revision: Union[str, Sequence[str], None] = 'c9a8516ab1ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_status', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('vehicle_status', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column(
        'vehicle_status',
        sa.Column(
            'is_charging',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('false'),
        ),
    )
    op.add_column('vehicle_status', sa.Column('is_plugged', sa.Boolean(), nullable=True))
    op.add_column('vehicle_status', sa.Column('total_range_km', sa.Float(), nullable=True))
    op.add_column('vehicle_status', sa.Column('remaining_charge_minutes', sa.Integer(), nullable=True))
    op.add_column('vehicle_status', sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('vehicle_status', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('vehicle_status', 'battery_level',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_index(op.f('ix_vehicle_status_vehicle_id'), 'vehicle_status', ['vehicle_id'], unique=False)
    op.drop_constraint(op.f('vehicle_status_vehicle_id_fkey'), 'vehicle_status', type_='foreignkey')
    op.create_foreign_key(None, 'vehicle_status', 'vehicles', ['vehicle_id'], ['id'], ondelete='CASCADE')
    op.drop_column('vehicle_status', 'doors_locked')
    op.alter_column('vehicles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('vehicle_status', sa.Column('doors_locked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vehicle_status', type_='foreignkey')
    op.create_foreign_key(op.f('vehicle_status_vehicle_id_fkey'), 'vehicle_status', 'vehicles', ['vehicle_id'], ['id'])
    op.drop_index(op.f('ix_vehicle_status_vehicle_id'), table_name='vehicle_status')
    op.alter_column('vehicle_status', 'battery_level',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('vehicle_status', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('vehicle_status', 'raw_payload')
    op.drop_column('vehicle_status', 'remaining_charge_minutes')
    op.drop_column('vehicle_status', 'total_range_km')
    op.drop_column('vehicle_status', 'is_plugged')
    op.drop_column('vehicle_status', 'is_charging')
    op.drop_column('vehicle_status', 'longitude')
    op.drop_column('vehicle_status', 'latitude')
    # ### end Alembic commands ###
